// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmdcTugzJV_vivzIUEf-7RnxEnIkQxF9E',
    appId: '1:909406114843:web:2c7b481b0e90b5075314be',
    messagingSenderId: '909406114843',
    projectId: 'charity-app-85be2',
    authDomain: 'charity-app-85be2.firebaseapp.com',
    storageBucket: 'charity-app-85be2.firebasestorage.app',
    measurementId: 'G-HP7ZYY1ML5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7dfZ0a1z-rFuCCLkNpyZOVi7CqQyu-Cc',
    appId: '1:909406114843:android:c1b7f772cce39b1f5314be',
    messagingSenderId: '909406114843',
    projectId: 'charity-app-85be2',
    storageBucket: 'charity-app-85be2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoYC0cpVRBevjds3lVkUnMO8gR5Df3XMU',
    appId: '1:909406114843:ios:da6d389c3a2e95565314be',
    messagingSenderId: '909406114843',
    projectId: 'charity-app-85be2',
    storageBucket: 'charity-app-85be2.firebasestorage.app',
    iosClientId: '909406114843-hl4t3dke78u1tokc36oud0phbjqqaoam.apps.googleusercontent.com',
    iosBundleId: 'com.example.charityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoYC0cpVRBevjds3lVkUnMO8gR5Df3XMU',
    appId: '1:909406114843:ios:da6d389c3a2e95565314be',
    messagingSenderId: '909406114843',
    projectId: 'charity-app-85be2',
    storageBucket: 'charity-app-85be2.firebasestorage.app',
    iosClientId: '909406114843-hl4t3dke78u1tokc36oud0phbjqqaoam.apps.googleusercontent.com',
    iosBundleId: 'com.example.charityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmdcTugzJV_vivzIUEf-7RnxEnIkQxF9E',
    appId: '1:909406114843:web:af68c090bb7402005314be',
    messagingSenderId: '909406114843',
    projectId: 'charity-app-85be2',
    authDomain: 'charity-app-85be2.firebaseapp.com',
    storageBucket: 'charity-app-85be2.firebasestorage.app',
    measurementId: 'G-0C3XYCF0XV',
  );
}
